name: "Commit"

on:
  workflow_dispatch:
    inputs:
      message:
        description: "Commit message"
        required: true

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd .githun/resources/commit
          echo "hoge\n" >> tmp.txt
          git add .
          git commit "${{ github.event.inputs.message }}"
          git push

