name: "Commit"

on:
  workflow_dispatch:
    inputs:
      message:
        description: "Commit message"
        required: true

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "hoge\n" >> resources/commit/tmp.txt
          git add .
          git commit -m "${{ github.event.inputs.message }}"
          git push

