# https://docs.github.com/ja/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idneeds
name: "Parallelized"

on:
  workflow_dispatch: {}

jobs:
  blocker:
    runs-on: ubuntu-latest
    steps:
      - name: "blocker"
        run: echo "blocker"

  parallelized1:
    runs-on: ubuntu-latest
    needs: blocker
    steps:
      - name: "parallelized1"
        run: echo "parallelized1"

  parallelized2:
    runs-on: ubuntu-latest
    needs: blocker
    steps:
      - name: "parallelized2"
        run: echo "parallelized2"

  nonblock_parallelized:
    runs-on: ubuntu-latest
    steps:
      - name: "nonblock_parallelized"
        run: echo "nonblock_parallelized"

  aggregate:
    runs-on: ubuntu-latest
    needs:
      - parallelized1
      - parallelized2
      - nonblock_parallelized
    steps:
      - name: "aggregate"
        run: echo "aggregate"

